 analysis:
   output_path:  "./test_data/results/sinca"
   debug: True
 
 data:
   SINCA:
      path: "./test_data/data/SINCA*.nc"
      topology: PointSurface
      reader: SINCA
      vars:
         PM10:
          name: PM10_ug|m3
          unit: "ug/m**3"
         PM25:
          name: PM25_ug|m3
          unit: "ug/m**3"
 plots:
   TC:
     type: timecycle
     base: "SINCA"
     time_interval: "1/1/2010-1/1/2025"
     timestep: "D"
     time_buckets: "day"
     vars:
       PM10: "ug/m**3"
       PM25: "ug/m**3"